FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy backend files
COPY backend/ /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy configuration (exclude local config file)
RUN mkdir -p /app/config
COPY config/assistant-config-example.yaml /app/config/

ENV PORT=8080

# Expose port
EXPOSE 8080

RUN chmod -R a+rX /app

# Run the application
CMD ["python", "app.py"]
